language: java
jdk:
- oraclejdk15
script:
- "./mvnw clean install -DskipTests"
cache:
 directories:
    - '$HOME/.m2/repository'
deploy:
  provider: heroku
  app: gameshow-api
  api_key: $HEROKU_TOKEN

branches:
  only:
    - master
