server:
  port: 8080
spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USRNAME}
    password: ${DATASOURCE_PWD}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

twitch:
  url: https://api.twitch.tv/kraken

app:
  secret: ${APP_SECRET}
  tokenValidityInSeconds: 86400000

igdb:
  url: https://api.igdb.com/v4
  urlToken: https://id.twitch.tv/oauth2/token
  client_id: ${CLIENT_ID}
  client_secret: ${CLIENT_SECRET}

discord:
  webhook_request: ${DISCORD_REQUEST}
  webhook_ticket: ${DISCORD_TICKET}

security:
  firebase-props:
    database-url: ${FIREBASE_DATABASE}
    enable-strict-server-session: false
    enable-check-session-revoked: false
    enable-logout-everywhere: false
    session-expiry-in-days: 5
  cookie-props:
    max-age-in-minutes: 7200
    http-only: true
    secure: true
    domain: ${DOMAIN}
    path: /
  allow-credentials: true
  allowed-origins:
    - https://${DOMAIN}
    - http://localhost:8100
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token
  allowed-public-apis:
    - /favicon.ico
    - /session/login
    - /public/**
  exposed-headers:
    - X-Xsrf-Token
